xmltv: pid handling && exit if input is empty

diff --git a/build/base/usr/local/bin/channels2m3u b/build/base/usr/local/bin/channels2m3u
--- a/build/base/usr/local/bin/channels2m3u
+++ b/build/base/usr/local/bin/channels2m3u
@@ -42,11 +42,13 @@ tvgChNo="${tvgChNo:-"1"}"
 silent="${silent:-"false"}"
 logVerbose="${logVerbose:-"false"}"
 
+PIDfile="/tmp/${0##*/}.pid"
+
 declare -a arrOutput
 
 
 ## CleanUp if killed
-trap 'printf "\n%s\n" "KILLED!"; exit 130' INT
+trap 'printf "\n%s\n" "KILLED!"; rm -f "$PIDfile"; exit 130' INT
 
 
 ## Functions
@@ -110,8 +112,17 @@ _CheckURL () {
 }
 
 
+## PID handling
+if [ -f "$PIDfile" ] && ps -p "$(cat "$PIDfile")" > /dev/null; then		# ensure only one instance of script is running
+	_log err 'Another instance of this script is running!\n' exit
+else
+	printf '%s' "$$" > "$PIDfile"	# write script's PID to pid-file
+fi
+
+
 ## Check input and output file/dir
 [ ! -r "$vdrChannels" ] && _log err "cannot read '$vdrChannels'!" exit
+[ ! -s "$vdrChannels" ] && _log err "'$vdrChannels' is empty!" exit
 [ ! -w "$outDIR" ] && _log err "cannot write into '$outDIR'!" exit
 [ -e "$m3uChannels" ] && [ ! -w "$m3uChannels" ] && _log err "'$m3uChannels' is not writable!" exit
 
@@ -183,7 +194,7 @@ for i in "${arrayChannel[@]}"; do
 			printf -v m3uExtInf '#EXTINF:-1 tvg-id="%s" tvg-chno="%s" tvg-name="%s" radio="%s" tvg-logo="%s" group-title="%s",%s' "$tvgID" "$tvgChNo" "$tvgName" "$radio" "$tvgLogo" "$tvgGroupTitle" "$tvgName"
 		fi
 
-        m3uURL="$m3uBaseURL/$tvgID"
+		m3uURL="$m3uBaseURL/$tvgID"
 
 		# Output
 		arrOutput+=( "$m3uExtInf" )
@@ -204,6 +215,10 @@ _log "Write file $m3uChannels"
 	printf '#EXTM3U tvg-shift="0"\n'
 	printf "%b\n" "${arrOutput[@]}"
 }  > "$m3uChannels"
+
+
+## CleanUp
+rm -f "$PIDfile"
 
 
 ## Done
