cosmetics

diff --git a/build/base/usr/lib/vdr/bin/vdr-recordingaction b/build/base/usr/lib/vdr/bin/vdr-recordingaction
--- a/build/base/usr/lib/vdr/bin/vdr-recordingaction
+++ b/build/base/usr/lib/vdr/bin/vdr-recordingaction
@@ -30,20 +30,20 @@ REC_HOOKS_DIR="/etc/vdr/recording-hooks"
 recordinghooks=`find "$REC_HOOKS_DIR" -maxdepth 1 -xtype f | sort`
 
 for recordinghook in $recordinghooks; do
-    case $1 in
-        before|after)
-            action="$1 recording $2"
-            ;;
-        edited)
-            action="after cutting recording $2 from $3"
-            ;;
-    esac
-    if [ -x $recordinghook ]; then
-        logger -t recordingaction "executing $recordinghook $action"
-        $recordinghook "$@"
-    else
-        logger -t recordingaction "executing $recordinghook $action as shell script"
-        /bin/sh $recordinghook "$@"
-    fi
-    [ $? -ne 0 ] && logger -t recordingaction "error when executing $recordinghook"
+	case $1 in
+		before|after)
+			action="$1 recording $2"
+			;;
+		edited)
+			action="after cutting recording $2 from $3"
+			;;
+	esac
+	if [ -x $recordinghook ]; then
+		logger -t recordingaction "executing $recordinghook $action"
+		$recordinghook "$@"
+	else
+		logger -t recordingaction "executing $recordinghook $action as shell script"
+		/bin/sh $recordinghook "$@"
+	fi
+	[ $? -ne 0 ] && logger -t recordingaction "error when executing $recordinghook"
 done
