improvement of the plugin installation and the local pkgbuild

diff --git a/build/base/etc/s6-overlay/scripts/local-packages_up b/build/base/etc/s6-overlay/scripts/local-packages_up
--- a/build/base/etc/s6-overlay/scripts/local-packages_up
+++ b/build/base/etc/s6-overlay/scripts/local-packages_up
@@ -2,108 +2,123 @@
 # shellcheck shell=bash
 
 
-# quit if AUR is disabled
-if [ "$AUR" = "false" ]; then
-	echo "AUR is disabled!"
+# quit if AUR is disabled or if no internet connection
+if [ "${AUR:-"true"}" = 'false' ]; then
+	printf 'AUR is disabled!\n'
+	exit 0
+elif [ "${NO_INET:-"false"}" = 'true' ]; then
+	printf 'No internet connection!\n'
 	exit 0
 fi
 
 
 # read pkg extension
-makepkg_conf="/etc/makepkg.conf"
+makepkg_conf='/etc/makepkg.conf'
 
 if [ -f "$makepkg_conf" ]; then
-	pacext=$(grep -v "^#" "$makepkg_conf" | grep -w "^PKGEXT=" | cut -d "=" -f 2 | tr -d "'")
+	pacext=$(grep -v '^#' "$makepkg_conf" | grep -w '^PKGEXT=' | cut -d '=' -f 2 | tr -d "'")
 	if [ -z "$pacext" ]; then
-		echo "Package extension not found, use default: '.pkg.tar.zst'"
-		pacext=".pkg.tar.zst"
+		pacext='.pkg.tar.zst'
+		printf 'Package extension not found, use default: "%s"\n' "$pacext"
 	fi
 fi
 
 
-bUser="builduser"
-pkgb_dir="/etc/PKGBUILD.d"
-buildDir="/var/cache/paru/user_pkg"
-vdrplug_conf="/etc/conf.d/user_plugins.conf"
-pacbuild="sudo -u $bUser makepkg --clean --install --noconfirm --noprogressbar --syncdeps --rmdeps"
-pacinst="paru --nouseask --noconfirm --noprogressbar --overwrite ´/usr/bin/*´ -U *$pacext"
+bUser='builduser'
+pkgb_dir='/etc/PKGBUILD.d'
+buildDir='/var/cache/paru/user_pkg'
+vdrplug_conf='/etc/conf.d/user_plugins.conf'
+
+
+_pacbuild() {		# buildDIR (buildUSER)
+	local bDIR="$1"
+	local bUSR=${2:-"$bUser"}
+	cd "$bDIR" || return 1
+	sudo -u "${bUSR}" makepkg --clean --noconfirm --noprogressbar --syncdeps --rmdeps
+}
+
+_pacinst() {		# packages to install
+	paru --nouseask --noconfirm --noprogressbar --overwrite '/usr/bin/*' -U "$@"
+}
 
 
 # array of subdirs sorted alphabetically
 mapfile -t package < <(find "$pkgb_dir/" -mindepth 1 -maxdepth 1 -type d | LC_ALL=C sort -f)
 
 
+# Profit!
 for DIR in  "${package[@]}"; do
 
 	pacname=$(basename "$DIR")
 	dirmd5=$(find "$DIR" -type f \( ! -iname "rebuild" \) | LC_ALL=C sort | tar --mode="664" --owner="65534" --group="65534" -cf - -T - 2>/dev/null | md5sum | cut -d " " -f 1)
 
-	echo "****** USER PACKAGE: $pacname ******"
+	printf '****** USER PACKAGE: %s ******\n' "$pacname"
 
 	# detox dir name
-	pacname=$(echo "$pacname" | sed -e 's/[^A-Za-z0-9._-]/_/g' | sed 's/^_//g' | sed 's/_$//g')
-	pacdir="$buildDir/$pacname"
-	md5file="$pacdir/md5sum"
-
+	pacname=$(printf '%s' "$pacname" | sed -e 's/[^A-Za-z0-9._-]/_/g' | sed 's/^_//g' | sed 's/_$//g')
+	pacdir="${buildDir}/${pacname}"
+	md5file="${pacdir}/md5sum"
 
 	# skip if md5sum matches or if PKGBUILD is missing
 	if [ -f "$md5file" ] && [ "$dirmd5" = "$(cat "$md5file" 2>/dev/null)" ] && [ ! -f "$DIR/rebuild" ]; then
-		echo "Nothing to do!"
+		printf 'Nothing to do!\n'
 		continue
 	elif [ ! -f "$DIR/PKGBUILD" ]; then
-		echo "Missing PKGBUILD file!"
+		printf 'Missing PKGBUILD file!\n'
 		continue
 	fi
 
-
+	# prepare build directory
 	if [ ! -d "$pacdir" ]; then
-		echo "create build dir..."
+		printf 'create build dir...\n'
 		mkdir -p "$pacdir"
 		chown -R $bUser:users "$buildDir"
 	else
-		echo "clear build dir..."
+		printf 'clear build dir...\n'
 		rm -rf "${pacdir:?}/"{*,.*} 2>/dev/null
 	fi
 
-	echo "copy to build dir..."
+	# copy everything to build directory
+	printf 'copy to build dir...\n'
 	cp -a "$DIR/." "$pacdir/"
 	chown -R $bUser:users "$pacdir"
-	cd "$pacdir" || exit 1
 
+	# forced dependencies handling
 	if [ -f "$DIR/forcedeps" ]; then
-		echo "force install dependencies..."
+		printf 'force install dependencies...\n'
 		mapfile -t mkdeps < <(< "$pacdir/PKGBUILD" awk "/.*makedepends=\(/,/\)/" | sed "s/makedepends=(//g" | sed "s/)//g" | xargs -n 1)
-		pacman -S --overwrite "/usr/bin/*" --needed --asdeps --noconfirm "${mkdeps[@]}"
-		forcedeps="true"
+		pacman -S --overwrite '/usr/bin/*' --needed --asdeps --noconfirm "${mkdeps[@]}"
+		forcedeps='true'
 	fi
 
-	echo "build package..."
-	$pacbuild || continue
+	# build
+	printf 'build package...\n'
+	_pacbuild "$pacdir" || continue
 
-	echo "install package..."
-	$pacinst || continue
+	# install
+	printf 'install package...\n'
+	_pacinst "${pacdir}"/*"${pacext}" || continue
 
-	echo "cleanup..."
+	# cleanup and removal of forced dependencies
+	printf 'cleanup...\n'
 	rm -rf "${pacdir:?}/"{*,.*} 2>/dev/null
 	rm -f "$DIR/rebuild"
-	echo "$dirmd5" > "$md5file"
-	if [ ${forcedeps:="false"} = "true" ]; then
+	printf '%s' "$dirmd5" > "$md5file"
+	if [ "${forcedeps:="false"}" = 'true' ]; then
 		pacman --noconfirm -R "$(pacman -Qtdq)" 2>/dev/null || true
 	fi
 
-
 	# enable VDR plugin if control file exists
-	#if [ 0 -lt "$(ls "$DIR/vdrplug-"* 2>/dev/null | wc -w)" ]; then
 	if [ 0 -lt "$(find "$DIR" -maxdepth 1 -type f -name 'vdrplug-*' 2>/dev/null | wc -w)" ]; then
-		vdrplug=$(find "$DIR" -maxdepth 1 -type f -name "vdrplug-*" -exec basename {} \; | LC_ALL=C sort -f | head -n 1 | sed 's/^vdrplug-//')
+		vdrplug=$(find "$DIR" -maxdepth 1 -type f -name 'vdrplug-*' -exec basename {} \; | LC_ALL=C sort -f | head -n 1 | sed 's/^vdrplug-//')
 		if ! grep -q "$vdrplug" "$vdrplug_conf"; then
-			echo "enable vdr-plugin $vdrplug..."
-			echo "$vdrplug" >> "$vdrplug_conf"
+			printf 'enable vdr-plugin %s...\n' "$vdrplug"
+			printf '%s\n' "$vdrplug" >> "$vdrplug_conf"
 			# only enable if disabled
-			enabled=$(vdrctl list --enabled | grep "^epg2vdr$" &>/dev/null && echo "true")
-			if [ "$enabled" != "true" ]; then
+			enabled=$(vdrctl list --enabled | grep "^$vdrplug$" &>/dev/null && printf 'true')
+			if [ "$enabled" != 'true' ]; then
 				vdrctl enable "$vdrplug" && \
-				echo "VDR-Plugin $vdrplug enabled."
+				printf 'VDR-Plugin %s enabled.\n' "$vdrplug"
 			fi
 		fi
 	fi
diff --git a/build/base/etc/s6-overlay/scripts/vdr-plugins_up b/build/base/etc/s6-overlay/scripts/vdr-plugins_up
--- a/build/base/etc/s6-overlay/scripts/vdr-plugins_up
+++ b/build/base/etc/s6-overlay/scripts/vdr-plugins_up
@@ -2,38 +2,37 @@
 # shellcheck shell=bash
 
 
+AUR="${AUR:-"true"}"
+UNINSTALL_PLUGINS="${UNINSTALL_PLUGINS:-"false"}"
+NO_INET="${NO_INET:-"false"}"
+
 if [ -z "$PLUGINS" ]; then
 	PLUGINS="epgsearch live streamdev-server vnsiserver"
-	echo "Using default VDR-Plugins: $PLUGINS"
+	printf 'Using default VDR-Plugins: %s\n' "$PLUGINS"
 fi
 
-if [ -z "$UNINSTALL_PLUGINS" ]; then
-	UNINSTALL_PLUGINS="false"
-fi
-
-if [ "$AUR" = "false" ]; then
-	pac_man="pacman"
+if [ "$AUR" = 'false' ]; then
+	pac_man='pacman'
 	installer="$pac_man"
-elif [ -z "$AUR" ] || [ "$AUR" != "false" ]; then
-	AUR="true"
-	bUser="builduser"
-	pac_man="paru"
-	installer="sudo -u $bUser $pac_man --nouseask --removemake --cleanafter"
+else
+	bUser='builduser'
+	pac_man='paru'
+	installer="sudo -u ${bUser} ${pac_man} --nouseask --removemake --cleanafter"
 fi
 
 mapfile -t enabled_arr < <(vdrctl list --enabled)
-mapfile -d ' ' -t plug_arr < <(printf '%s ' "$PLUGINS")
+read -ra plug_arr <<<"${PLUGINS,,}"
 
 
 # plugins added by user
-uplug_conf="/etc/conf.d/user_plugins.conf"
+uplug_conf='/etc/conf.d/user_plugins.conf'
 
 if [ -f "$uplug_conf" ]; then
 	while read -r uplug; do
 		if [[ "$uplug" =~ ^#.*$ ]]; then
 			continue
 		else
-			echo "User VDR-Plugin '$uplug' was recognized..."
+			printf 'User VDR-Plugin "%s" was recognized...\n' "$uplug"
 			plug_arr+=("$uplug")
 		fi
 	done < "$uplug_conf"
@@ -41,14 +40,14 @@ fi
 
 
 # live plugin handling
-if [[ ! "${plug_arr[*]}" =~ "live" ]] && [ "$DISABLE_WEBINTERFACE" != "true" ]; then
-	echo "Keep live plugin enabled..."
-	plug_arr+=("live")
-elif [[ "${plug_arr[*]}" =~ "live" ]] && [ "$DISABLE_WEBINTERFACE" = "true" ]; then
-	echo "VDR-Plugin live is disabled via the environment variable 'DISABLE_WEBINTERFACE=true'!"
+if [[ ! "${plug_arr[*]}" =~ 'live' ]] && [ "$DISABLE_WEBINTERFACE" != 'true' ]; then
+	printf 'Keep live plugin enabled...\n'
+	plug_arr+=('live')
+elif [[ "${plug_arr[*]}" =~ "live" ]] && [ "$DISABLE_WEBINTERFACE" = 'true' ]; then
+	printf 'VDR-Plugin live is disabled via the environment variable "DISABLE_WEBINTERFACE=true"!\n'
 	# delete plugin live from array
 	for i in "${!plug_arr[@]}"; do
-		if [[ ${plug_arr[i]} = "live" ]]; then
+		if [[ ${plug_arr[i]} = 'live' ]]; then
 			unset 'plug_arr[i]'
 		fi
 	done
@@ -57,29 +56,25 @@ fi
 
 _isAvailable() {
 	local plugin=$1;
-	local avail
-	avail=$($pac_man -Ssq "$plugin" 2> /dev/null | grep "^$plugin$")
-	if [  -n "$avail" ]; then
-		echo 0	# Success
+	if $pac_man -Ssq "$plugin" 2> /dev/null | grep -q "^$plugin$"; then
+		printf '0'	# Success
 	else
-		echo 1	# Error
+		printf '1'	# Error
 	fi
 }
 
 _isInstalled() {
 	local package=$1
 	$pac_man -Qi "$package" &> /dev/null
-	echo $?
+	printf '%s' $?
 }
 
 _isEnabled() {
 	local plugin=$1;
-	local enabled
-	enabled=$(vdrctl list --enabled | grep "^$plugin$")
-	if [ "$enabled" = "$plugin" ]; then
-		echo 0	# Success
+	if vdrctl list --enabled | grep -q "^$plugin$"; then
+		printf '0'	# Success
 	else
-		echo 1	# Error
+		printf '1'	# Error
 	fi
 }
 
@@ -88,10 +83,10 @@ for en_plug in  "${enabled_arr[@]}"; do
 	# Plugin not in array but enabled
 	if [[ ! "${plug_arr[*]}" =~ $en_plug ]]; then
 		vdrctl disable "$en_plug" && \
-		echo "Plugin $en_plug disabled."
-		if [ "$UNINSTALL_PLUGINS" = "true" ]; then
-			echo "VDR-Plugin $en_plug not uninstalled!"
-			echo "Uninstalling VDR-Plugins is currently not supported..."
+		  printf 'Plugin %s disabled.\n' "$en_plug"
+		if [ "$UNINSTALL_PLUGINS" = 'true' ]; then
+			printf 'VDR-Plugin %s not uninstalled!\n' "$en_plug"
+			printf 'Uninstalling VDR-Plugins is currently not supported...\n'
 		fi
 	fi
 done
@@ -100,32 +95,48 @@ done
 for plug in  "${plug_arr[@]}"; do
 	pacname="vdr-$plug"
 
-	# Plugin available
-	if [ "$(_isAvailable "$pacname")" = "0" ]; then
-		plg_avail="true"
-	else
-		plg_avail="false"
-		echo "VDR-Plugin $plug is not available in repository!"
-	fi
-
 	# Plugin installed
-	if [ "$(_isInstalled "$pacname")" = "0" ]; then
-		plg_inst="true"
+	if [ "$(_isInstalled "$pacname")" = '0' ]; then
+		plg_inst='true'
 	else
-		plg_inst="false"
-		echo "VDR-Plugin $plug is not installed."
+		plg_inst='false'
+		printf 'VDR-Plugin %s is not installed.\n' "$plug"
 	fi
 
-	# Plugin not installed but available
-	if [ $plg_inst != "true" ] && [ $plg_avail = "true" ]; then
-		## use "overwrite" because of busybox
-		$installer -S --overwrite "/usr/bin/*" --noprogressbar --noconfirm "$pacname" && \
-		activate_plug="true"
+	# Plugin enabled
+	if [ "$(_isEnabled "$plug")" = '0' ]; then
+		plg_enabled='true'
+	else
+		plg_enabled='false'
+		printf 'VDR-Plugin %s is not enabled.\n' "$plug"
 	fi
 
-	# Plugin installed and disabled
-	if [[ $plg_inst = "true" || ${activate_plug:="false"} = "true" ]] && [ "$(_isEnabled "$plug")" = "1" ]; then
+	# No Internet Connection
+	if [ "$NO_INET" != 'true' ]; then
+		# Plugin available
+		if [ "$(_isAvailable "$pacname")" = '0' ]; then
+			plg_avail='true'
+		else
+			plg_avail='false'
+			printf 'VDR-Plugin %s is not available in repository!\n' "$plug"
+		fi
+
+		# Plugin not installed but available
+		if [ $plg_inst != 'true' ] && [ $plg_avail = 'true' ]; then
+			# use "overwrite" because of busybox
+			$installer -S --overwrite '/usr/bin/*' --noprogressbar --noconfirm "$pacname" && \
+			 plg_inst='true'		# mark as installed if successful
+		fi
+	fi
+
+	# Plugin (not) installed and dis/enabled
+	if [ $plg_inst = 'true' ] && [ "$plg_enabled" = 'false' ]; then
 		vdrctl enable "$plug" && \
-		echo "VDR-Plugin $plug enabled."
+		printf 'VDR-Plugin %s enabled.\n' "$plug"
+	elif [ $plg_inst = 'false' ] && [ "$plg_enabled" = 'true' ]; then
+		vdrctl disable "$plug" && \
+		printf 'VDR-Plugin %s disabled.\n' "$plug"
 	fi
+
+	unset plg_avail plg_enabled plg_inst
 done
